hosts:
  - localhost:8091
username: user
password: password
bucketName: dcp-test
dcp:
  group:
    name: groupName
metadata:
  type: couchbase
  config:
    bucket: dcp-test-meta
    scope: _default
    collection: _default
couchbase:
  hosts:
    - localhost:8091
  username: user
  password: password
  bucketName: dcp-test-backup